### PR TITLE
Add statFactor for entropyGain

### PR DESCRIPTION
**Pull request by oorzkws**
Mods can access this by patching `modExtensions/li[@Class="VanillaPsycastsExpanded.AbilityExtension_Psycast"]` to add an entropyGainStatFactors entry, similar to how AbilityBase implements rangeStatFactors

I've backported it to 1.3 for the players still on that branch for the short-term as they complete their saves, you're welcome to exclude that commit if you see fit.

### CODE REVIEW

**Comment by oorzkws** [comment]
@legodude17 could I bother you to take a look at this? I have a mod release waiting on the PR for around a month now. If you're busy it's no problem, just want to avoid having to rebase and recompile again.

**Comment by legodude17** [comment]
Looks good!

**Comment by legodude17** [comment]
Should be pushed to steam now!

**Comment by oorzkws** [comment]
> Should be pushed to steam now!

Thanks for the quick push! Demo mod [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2881380497) should let folks tweak the balance as they desire.

**Pull request merged**
